* Get stuff - npm, binaries (including Windows), homebrew all available.

** Official docs:

  https://github.com/purescript/documentation

** Official recommended tooling is Pulp/Bower and the purescript compiler purs.

   I did not use them. We're gonna use spago today:

  https://github.com/spacchetti/spago

** Editor tooling available for atom, VSCode, vim, emacs, etc

* Purescript

** A small-ish Haskell-like ML family language that compiles to readable JavaScript

*** I'm going to assume you know and love Haskell, so here's how they are similar

**** System F ω plus some stuff

**** Two semicolons for type annotations

*** Here's how they differ

**** Typeclass heirarchies different

**** Explicit forall

**** Row types

**** Strict evaluation

**** Nicer records

**** Extensible Records

** An excellent playground for writing frontend architectures

  - Thermite - wrapper around react
  - Pux - slightly more principled wrapper around react
  - Comonad experiments by Phil Freeman
  - choco pie - a cycleJS like thing
  - et cetera

* Halogen

** A library for creating managed-state frontend applications

** (Theoretically) pluggable rendering engines (HTML, React?, iOS? android?)

** Maintained and used by slamdata

** Comparing to elm: Casually speaking - Halogen uses Free where elm (and redux) use something like CoFree

   You will notice they feel dual to each other as we go

** Following is a demo that mostly covers the halogen tutorial plus a little more

   https://github.com/slamdata/purescript-halogen/tree/v4.0.0/docs/

* Addendum

** FFI is great:

   - Import values or types (values shown below)

#+BEGIN_SRC purescript
-- src/Math.purs
module Math where
foreign import pow :: Number -> Number -> Number
#+END_SRC

#+BEGIN_SRC js
// src/Math.js
"use strict";
exports.pow = function(x) {
  return function(y) {
    return Math.pow(x,y);
  };
};
#+END_SRC

** Routing possible through ~receivers~ of components

** Excellent lens implementation (profunctors)

** Other great libraries

*** Formless - don't manage state or render your own forms anymore

*** Remote Data ported from elm
